### ISSUE TITLE
Code examples are unreadable

### ISSUE THREAD

**Issue by ktonsber** [StanfordVLSI/Genesis2#1]
The code examples on this page are unreadable, probably due to badly formatted HTML. A screenshot is attached.
This issue is present on both of the browsers that I have installed, Chrome and Internet Explorer.
![image](https://user-images.githubusercontent.com/82801917/118933376-66993580-b949-11eb-8859-ff59a254d14a.png)

**Comment by steveri** [comment]
It would be helpful if you included a pointer to the page in question...ah here it is?
https://github.com/StanfordVLSI/Genesis2/wiki/Source-Code-Structure
You're right that's pretty terrible, I'll see if I can fix it.
Thanks @ktonsberg !

**Comment by steveri** [comment]
Okay @ktonsber I think I fixed all the examples on this page, see if you can read them now, then we can close this issue.

Meanwhile, I will put it on my to-do list to find and scrub all similar examples throughout the wiki...

**Comment by ktonsber** [comment]
Thanks, it looks much better now 😊

/Kasper

**Comment by steveri** [comment]
Thanks Kasper
- Steve
